apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.webScheduler.airflowCfgConfigMap }}"
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
  labels:
    app: {{ template "airflow.name" . }}
    chart: {{ template "airflow.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  airflow.cfg: |-
{{ tpl (.Files.Get "airflow.cfg") . | indent 4 }}